### ISSUE TITLE
Don't Work (Hp Spectre 13)

### ISSUE THREAD

**Issue by Master-Antonio** [koseduhemak/touchpadswipe#1]
Hello .
Your extension with the hp spectre 13 (i5 7200U) don't work.
The touchpad is a Synaptics.
Software Version : 19.3.11.31

**Comment by koseduhemak** [comment]
Hello,

thank you for your feedback.

Please provide me some more info:
- Are you able to scroll **horizontally** with two fingers in a Browser Window?
- If not, does scrolling with one finger work on your laptop (vertical & horizontal)?

You can enable horizontal scrolling f.e. like so: [Guide to enable two finger scrolling in driver](http://www.howtogeek.com/howto/35065/how-to-enable-macbook-style-two-finger-scrolling-on-windows-laptops/)

Background: The extension listened for horizontal scrolling events, so if horizontal scrolling works the extension should also work.

**Comment by koseduhemak** [comment]
closing - havent got any feedback about it.
