### ISSUE TITLE
Permission concerns

### ISSUE THREAD

**Issue by Razzpekt** [koseduhemak/touchpadswipe#15]
Hi everyone,
First of all, I am not sure if this is the right place for my concerns, but I did not find anywhere else to express them. If there is one, let me know :)

I was about to install this extension in chrome when it asked me to grant permission to read and edit all data on my visited websites. Usually I am not that kind of guy who thinks too much about that, yet I got kinda curious why this permission needs to be granted for an extension which tracks my trackpad and presses the back button for me. I mean, what does this have to do with any data on the website? 
Actually I am not really concerned, more curious if this is necessary and if yes why.
 
Hope someone can explain this to me. 

Greetings

**Comment by koseduhemak** [comment]
Hello,

I can confirm this is odd, but it is needed for storing the options an user made, so the browser can load it after restart.

You can look into manifest.json within this repository to see which permissions are specified. The only one is "storage": https://developer.chrome.com/extensions/declare_permissions#manifest

Greetings

**Comment by Razzpekt** [comment]
Hey, thanks for your response and clarification. 
Like I said, it was more out of curiosity why I asked, didn't assume you actually steal my data.

I installed it already and like it very much.
Greetings
