### ISSUE TITLE
The extension can not be found on Chrome Store

### ISSUE THREAD

**Issue by pcmaniac23** [koseduhemak/touchpadswipe#20]
Following the link provided on the documentations page:
https://chrome.google.com/webstore/detail/touchpadswipe/hbolfopmehcpecgmcompfpgapnbgbhio

I get a 404 page cannot be found result from chrome webstore.

**Comment by fannyfan414** [comment]
Reinstall windows and found that it is no longer possible to install the extension

**Comment by koseduhemak** [comment]
Yes... Sadly the extension is no longer available through chrome web store. Google wanted me to add an explanation video / screenshots to the extension. I had no time for that so the extension got deleted. You can however create it by yourself (just google "how to load local extension") using the source from this repo.

**Comment by fannyfan414** [comment]
**Instruction how to enable extenstion**
Open [chrome://extensions/](url) in your chrome browser. In the upper right corner, turn on developer mode. Unzip this archive to your PC. Drag (Important!) src file with crx extension in chrome extensions page. Find touchpadswipe extension that appears in the list and turn it on if it is turned off.
[src.zip](https://github.com/koseduhemak/touchpadswipe/files/2875483/src.zip)

**Comment by koseduhemak** [comment]
If you want, I can put your explanations in the README file of the repo, so other users are more likely to see it.

**Comment by koseduhemak** [comment]
Added to README. I close here

**Comment by knittycatkitty** [comment]
Getting this issue here, 

<img width="403" alt="touchpadswipe" src="https://user-images.githubusercontent.com/42597963/53013611-0aa67600-33fb-11e9-98f6-a0c91c59e47c.PNG">

**Comment by knittycatkitty** [comment]
Got it to work by loading unpacked

**Comment by pcmaniac23** [comment]
@koseduhemak Thank you for making this great extension that made the experience of using Chrome even more enjoyable then it already is.

@fannyfan414 Thanks for providing a detailed instruction about how to make the extension usable again, great stuff!

**Comment by pcmaniac23** [comment]
@knittycatkitty I am getting the same error message as you had and I followed @fannyfan414 's installation instructions. Could you please explain what you meant by "getting it to work by loading unpacked" (I also unpacked the src.zip first then drag & dropped the src.crx to the chrome://extensions page) ??

**Comment by knittycatkitty** [comment]
> @knittycatkitty I am getting the same error message as you had and I followed @fannyfan414 's installation instructions. Could you please explain what you meant by "getting it to work by loading unpacked" (I also unpacked the src.zip first then drag & dropped the src.crx to the chrome://extensions page) ??

Download this repo, 

In chrome://extensions menu, click Load Unpacked and point to the src folder of the downloaded repo.

It will start unpacking it and circumvent the crx "install from webstore" requirement.

This is outside of the scope of touchpadswipe but Chrome Canary build also has touchpadswipe functionality built-in with visual pointers as well

**Comment by koseduhemak** [comment]
If one of you guys can make a screenshot / graphic which details how to use it and an icon, I can try to reupload it to the extension store...

You also can extract `src.zip` and rename `src.crx` to f.e. `touchpadswipe.zip`.  Then just extract touchpadswipe.zip too and drag the resulting folder to chrome://extensions page.

**Comment by knittycatkitty** [comment]
> If one of you guys can make a screenshot / graphic which details how to use it and an icon, I can try to reupload it to the extension store...
> 
> You also can extract `src.zip` and rename `src.crx` to f.e. `touchpadswipe.zip`. Then just extract touchpadswipe.zip too and drag the resulting folder to chrome://extensions page.

I can try to make something like this but the extension is lacking some visual pointers so it is mostly intuitive.

![image](https://user-images.githubusercontent.com/42597963/53024056-532a5780-342c-11e9-88b0-f71574cea072.png)

I'll put something together on Illustrator

**Comment by fannyfan414** [comment]
Guys, made a video with a phased installation.
Link from video in description
[https://youtu.be/Ik3M9snynZw](url)

**Comment by pcmaniac23** [comment]
@knittycatkitty Thanks for the explanation, I realized that I had to use the actual repo as source code by cloning it (I got confused by @fannyfan414 's src.zip) in order to follow your instruction successfully :D

@fannyfan414 Thanks for the 1 min video!

And here's what I found regarding screenshot/graphic that shows how to use the extension:
A .gif showing how Mac's swipe to go forward/backward works:
https://makeagif.com/gif/mac-trackpad-gestures-ItyQpi
https://makeagif.com/i/ItyQpi

As for icons, some possible ideas from Apple's support page:
https://support.apple.com/en-us/HT204895

**Comment by koseduhemak** [comment]
> I can try to make something like this but the extension is lacking some visual pointers so it is mostly intuitive.
> 
> ![image](https://user-images.githubusercontent.com/42597963/53024056-532a5780-342c-11e9-88b0-f71574cea072.png)
> 
> I'll put something together on Illustrator

Would be really nice! Make sure to use open images (licence free) or images where you have the right to use. Otherwise I may will get in trouble :) (I got already busted using non-licensed images in another project... So I am little bit carefully here now). Good place to start with licence free images: https://pixabay.com/

Image could also be just a sketch which demos the functionality (swipe right, swipe left).

@fannyfan414
I put your video in the README file. Thank you!

Thank you guys for your support!
