### ISSUE TITLE
The Firefox Downloads in Readme seems to be broken?

### ISSUE THREAD

**Issue by nutnutwin** [koseduhemak/touchpadswipe#22]
Hi, I tried the link below, 
https://addons.mozilla.org/en-US/firefox/addon/touchpadswipelikemac/

and searched on Firefox Extension, but found nothing

I remember installing your extension just a few months back...

Sorry is there anyway I can get the xpi install file? Or I can compile it myself somehow?

Thank you

**Comment by Jhaego** [comment]
I, too, would love for this extension to be available once again, if possible. It still perplexes me that this isn't a feature in Firefox.

**Comment by potato03kth** [comment]
in 2021 3Q either
would like to use extention...

**Comment by nutnutwin** [comment]
Stopped waiting and switched to Chrome
Closed
