### ISSUE TITLE
Swipe forward (right) doesn't work anymore

### ISSUE THREAD

**Issue by ghost** [koseduhemak/touchpadswipe#6]
Latest version of the extension (1.2.6) , Google Chrome (59.0.3071.104) and Windows 10 stable. (1703)

Swipe back with 2 fingers works great. Disabling animation helps speed it up.

But swipe forward with 2 fingers to the right doesn't work.

Dell XPS 13 (9360)

Hope you can fix it.

**Comment by koseduhemak** [comment]
Thank you for the report. I will look into it soon and post back.

**Comment by 1Claude** [comment]
Just to tell you I found a fix for swipe left and right in the advanced settings of the touchpad in Windows 10. 

https://www.addictivetips.com/windows-tips/three-finger-swipe-for-browser-navigation-windows-10/

**Comment by koseduhemak** [comment]
Ok will close this issue now. If needed just reopen it.
