### ISSUE TITLE
Firefox Release (it's working already)

### ISSUE THREAD

**Issue by maximilianoe** [koseduhemak/touchpadswipe#7]
I've tested your addon in Firefox 57 and it works (used [this website](http://crxextractor.com/) to get a crx file which I then extracted and temporarily installed as explained [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox))
Are there plans to officially release it in the Firefox Addon Store?

Here is a very simple guide for publishing Chrome extensions to AMO:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

![snip_20171022213903](https://user-images.githubusercontent.com/15032541/31865596-7f051446-b771-11e7-9ae8-78eb80baa552.png)

My setup:
Firefox 57.0b10
Microsoft Surface Laptop (Windows Precision Touchpad Drivers)

**Comment by koseduhemak** [comment]
Hello there!
Thank you for sharing this. I will definitely look into this - had no idea it is that easy ;)
As I am very busy at the moment, it can take me a week or two to submit the extension in the firefox addon store...
I will post here if it is live.

**Comment by koseduhemak** [comment]
Added extension to firefox addon store. Should be available soon at: 
https://addons.mozilla.org/en-GB/firefox/addon/touchpadswipelikemac/

Please test and report issues.

**Comment by maximilianoe** [comment]
I'll report back once it's available. Are there any specific modifications for the Firefox version or did you simply submit the Chrome extension without changes?

**Comment by FlipB** [comment]
The addon is available now.
Seems to work well so far.

**Comment by koseduhemak** [comment]
Thank you for testing. I will close this issue now.
