### ISSUE TITLE
Make available on firefox as an addon

### ISSUE THREAD

**Issue by pingio** [koseduhemak/touchpadswipe#9]
Since [firefox supports using chrome web extensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension) you should make it available on the firefox aswell.  
Tested the add-on on my Dell XPS 13 (9360) with firefox quantum version 57.0.4 and it worked flawlessly as a temporary add-on.  
The only thing that would have to be sorted for a release (I think), would be to [sign the add-on](https://wiki.mozilla.org/Add-ons/Extension_Signing).

**Comment by koseduhemak** [comment]
It is already in the mozilla addon store: https://addons.mozilla.org/de/firefox/addon/touchpadswipelikemac/

**Comment by pingio** [comment]
ah cheers, might I suggest updating the readme/repo description to include firefox then?

**Comment by koseduhemak** [comment]
of course! I plan to update the extension in the next few weeks with some bugfixes. At this time I will also update the readme with a link to the firefox addon store. I will leave this issue open till README gets updated.

**Comment by koseduhemak** [comment]
Updated ReadMe.
